### ISSUE TITLE
Incorrect xssp-rest url

### ISSUE THREAD

**Issue by jonblack** [cmbi/vase#10]
The URL for xssp-rest is incorrect:

```
private static String hsspRestURL = "http://127.0.0.1:5000/api";//"http://www.cmbi.ru.nl/xssp/api";
```

**Comment by cbaakman** [comment]
It seems to be fixed, looking at https://github.com/cmbi/vase/blob/master/src/main/java/nl/ru/cmbi/vase/web/rest/JobRestResource.java#L88
